takuma-ru/auto-story-generator

- docs/.vitepress/config.mts
- docs/.vitepress/theme/custom.css
- docs/faq.md
- FAQ追加
- テーマカラーをStorybooknに寄せた
> 📝 FAQ追加, テーマカラー更新

- .github/workflows/pr-check.yml
- .github/workflows/publish-package.yml
> 🐛 GitHub Release CI修正

- packages/auto-story-generator/src/index.ts
- packages/auto-story-generator/src/presets/lit/genLitStoryFile.ts
- packages/auto-story-generator/src/presets/lit/getLitPropTypes.ts
- packages/auto-story-generator/src/presets/react/genReactStoryFile.ts
- packages/auto-story-generator/src/presets/react/getReactPropTypes.ts
- packages/auto-story-generator/src/types/GenPropTypeType.ts
- packages/auto-story-generator/src/types/GenStoryFileType.ts
- packages/auto-story-generator/src/types/GetComponentInfo.ts
- packages/auto-story-generator/src/types/Options.ts
- packages/auto-story-generator/src/utils/genStoryFile.ts
- packages/auto-story-generator/src/utils/getComponentInfo.ts
> ♻️ Unification of variable names

- .github/release-drafter.yml
- .github/workflows/pr-check.yml
- .github/workflows/publish-package.yml
- .github/workflows/release-drafter.yml
- README.md
- demo/next/src/components/TestE/TestE.tsx
- packages/auto-story-generator/.release-it.cjs
- packages/auto-story-generator/README.md
- packages/auto-story-generator/package.json
- packages/auto-story-generator/src/presets/react/genReactStoryFile.ts
> 🛠️ [react] component is implemented with export default, output the import portion appropriately

- packages/auto-story-generator/package.json
> Release 0.2.3

- .github/workflows/pr-check.yml
- .github/workflows/publish-package.yml
- packages/auto-story-generator/.release-it.cjs
- packages/auto-story-generator/package.json
👷 Update publish-package.yml and .release-it.cjs
> 🛠️ Update release flow

- packages/auto-story-generator/.eslintrc.cjs
- packages/auto-story-generator/src/constants/error.ts
- packages/auto-story-generator/src/index.ts
- packages/auto-story-generator/src/presets/lit/genLitStoryFile.ts
- packages/auto-story-generator/src/presets/lit/getLitPropTypes.ts
- packages/auto-story-generator/src/presets/react/genReactStoryFile.ts
- packages/auto-story-generator/src/types/error.ts
- packages/auto-story-generator/src/utils/genStoryFile.ts
- packages/auto-story-generator/src/utils/throwError.ts
> 🛠️ Common processing when errors occur 

- packages/auto-story-generator/.release-it.cjs
Update release-it.cjs with post-release git commands
> 🐛 Failure release action

- .github/workflows/publish-package.yml
- packages/auto-story-generator/.release-it.cjs
> 💚  Add release branch creation and pull request creation

- .github/workflows/pr-check.yml
- .github/workflows/publish-package.yml
- demo/next/.storybook/main.ts
- demo/react/src/components/Test/Test.tsx
- packages/auto-story-generator/src/constants/error.ts
- packages/auto-story-generator/src/presets/react/getReactPropTypes.ts
- packages/auto-story-generator/src/types/Options.ts
- packages/auto-story-generator/src/types/error.ts
- packages/auto-story-generator/src/utils/getAllFilePaths.ts
Add error handling for non-existent directory in getAllFilePaths function.
> 🐛 Error when specifying a path that does not exist in imports

- packages/auto-story-generator/package.json
> :bookmark: release @takuma-ru/auto-story-generator@0.2.6

- .github/pull_request_template.md
- demo/next/src/components/TestC/index.tsx
- packages/auto-story-generator/src/presets/react/getReactPropTypes.ts
⚡️ getParameters()[0] が取得できなかった際に undefinedになるよう修正
- #43
> 🛠️ When a Prop does not exist, generate a story file with no Prop instead of an error

- packages/auto-story-generator/package.json
> :bookmark: release @takuma-ru/auto-story-generator@0.2.7

- .github/workflows/publish-package.yml
- .scripts/release.cjs
👷 Update publish-package.yml and add release.cjs script
- #56
> ✨ Implement your own release process

- packages/auto-story-generator/src/presets/lit/genLitStoryFile.ts
- packages/auto-story-generator/src/presets/lit/getLitPropTypes.ts
- packages/auto-story-generator/src/presets/react/genReactStoryFile.ts
- packages/auto-story-generator/src/presets/react/getReactPropTypes.ts
- packages/auto-story-generator/src/utils/removeQuotesAndWrapWithDoubleQuotes.ts
🐛 Fix string value formatting in genLitStoryFile and genReactStoryFile
- #55
> 🐛 When creating union props, there are no double quotes in the value set to args

- packages/auto-story-generator/package.json
> Release version 0.2.10

- .scripts/release.cjs
- docs/.vitepress/config.mts
- docs/errors.md
- docs/package.json
- packages/auto-story-generator/src/constants/error.ts
- packages/auto-story-generator/src/index.ts
- packages/auto-story-generator/src/utils/throwError.ts
- pnpm-lock.yaml
https://github.com/takuma-ru/auto-story-generator/issues/62
- #62
> 🐛 When the AST fails, the process drops out

- packages/auto-story-generator/package.json
> Release version 0.2.11

- demo/next/.storybook/main.ts
- packages/auto-story-generator/src/index.ts
- packages/auto-story-generator/src/utils/getAllFilePaths.ts
✨ getAllFilePaths の内部処理をglobに置換
- #65
> 🛠️ Transfers processing of getAllFilePaths to glob

- demo/react/.storybook/main.ts
- docs/introduction/getting-started.md
- docs/introduction/options.md
- packages/auto-story-generator/src/core/runGenStoryFile.ts
- packages/auto-story-generator/src/index.ts
- packages/auto-story-generator/src/types/Options.ts
> 🛠️ Add `options.ignores`

- packages/auto-story-generator/src/index.ts
Fixed import method for glob
- #71
> 🐛 Fixed import method for glob

- .gitignore
- packages/auto-story-generator/README.md
- packages/auto-story-generator/src/core/genStoryFile.ts
- packages/auto-story-generator/src/presets/react/genReactStoryFile.ts
- packages/auto-story-generator/src/types/GetComponentInfo.ts
- packages/auto-story-generator/src/types/Options.ts
Added the option to generate stories in folder, like `__stories__`.
- none
> ✨ Added Option to generate stories in folder
